######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 26 22:31:53 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug
CFLAGS +=  #QMAKE_*FLAGS are where the gcc flags should be passed
CXXFLAGS += 
# Input
SOURCES += i7z_GUI.cpp ../log.c
LIBS += -lncurses
