enum intel_procs {
    INTEL_NEHALEM,
    INTEL_WESTMERE,
    INTEL_SANDYBRIDGE,
    INTEL_IVYBRIDGE,
    INTEL_HASWELL,
    INTEL_BROADWELL,
    INTEL_SKYLAKE,
    INTEL_KABYLAKE,
    INTEL_CANNONLAKE
};
